version: '3'
services:
  django:
    image: django_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - "./django_app:/app"
    working_dir: /app
    command: manage.py runserver 0.0.0.0:8000