# Generated by Django 5.2.1 on 2025-06-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_post_content_post_genre_alter_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Movie',
        ),
    ]
