# Generated by Django 5.2.1 on 2025-06-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(default=2025)),
            ],
        ),
    ]
